// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP3EJsdhfX8KRixz2x-vUyQQjdf969OrQ',
    appId: '1:209667955295:web:1977a9d709921ac0f319ea',
    messagingSenderId: '209667955295',
    projectId: 'elearning-8a3f4',
    authDomain: 'elearning-8a3f4.firebaseapp.com',
    storageBucket: 'elearning-8a3f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1xvysXqlt96581XzdlslbqF2jVQcGlfM',
    appId: '1:209667955295:android:e1b5afa565c4f1fcf319ea',
    messagingSenderId: '209667955295',
    projectId: 'elearning-8a3f4',
    storageBucket: 'elearning-8a3f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6lQP8PvYw_OQJtMAlc2dymcWY6uZCZYs',
    appId: '1:209667955295:ios:63281c89504f616df319ea',
    messagingSenderId: '209667955295',
    projectId: 'elearning-8a3f4',
    storageBucket: 'elearning-8a3f4.firebasestorage.app',
    iosBundleId: 'com.example.elearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6lQP8PvYw_OQJtMAlc2dymcWY6uZCZYs',
    appId: '1:209667955295:ios:63281c89504f616df319ea',
    messagingSenderId: '209667955295',
    projectId: 'elearning-8a3f4',
    storageBucket: 'elearning-8a3f4.firebasestorage.app',
    iosBundleId: 'com.example.elearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP3EJsdhfX8KRixz2x-vUyQQjdf969OrQ',
    appId: '1:209667955295:web:c4755a82d1988937f319ea',
    messagingSenderId: '209667955295',
    projectId: 'elearning-8a3f4',
    authDomain: 'elearning-8a3f4.firebaseapp.com',
    storageBucket: 'elearning-8a3f4.firebasestorage.app',
  );
}
